### ISSUE TITLE
Resource server endpoints not functioning

### ISSUE THREAD

**Issue by poojan007** [SaiUpadhyayula/springboot-microservices-project#4]
When i try to hit the any of the resource server endpoints i get the keycloak login page returned, please help.

**Comment by SaiUpadhyayula** [comment]
@poojan007  I am aware of this, the workaround is to request a token using the client_credentials grant type instead of authorization_code grant type.

I am planning to check this issue for a long time, but I am not getting time to do it, but I really plan to work on it this weekend :)

Meanwhile, you can check on how to request a token using the client_credentials grant and use the resulting token to make a request to the Resource Server :)

**Comment by SaiUpadhyayula** [comment]
@poojan007 So here is the solution I found:

I updated the api-gateway project to include an endpoint to return a Session ID, check the ApiGatewayServiceApplication.java class.

Once you access the address http://localhost:8080 you should get a Keycloak Login screen, once you logged in, you will see the session id as the response.

![image](https://user-images.githubusercontent.com/4116717/120072836-f8194d80-c095-11eb-9732-8bfaa982d2a6.png)

Now you have to copy this session id and insert into the Header section of the Postman request.

Like below:

![image](https://user-images.githubusercontent.com/4116717/120072878-27c85580-c096-11eb-858a-e1203079c39b.png)

Now if you access the endpoint to place an order you will receive the response back from the Order Service

This should fix the problem.

If you are somehow lost on how to update the Headers section, you can download and import the Postman file. You just have to change the session id

https://github.com/SaiUpadhyayula/springboot-microservices-project/blob/master/Microservices%20Project.postman_collection.json

**Comment by javaHelper** [comment]
I am sending both Cookie and OAuth2 token and getting 401 not sure what still blocking me :(

![image](https://user-images.githubusercontent.com/54174687/120509466-28d6eb00-c3e6-11eb-90a0-ca1efbd3c449.png)

**Comment by javaHelper** [comment]
Thanks POST working fine now, but looks like GET is not working. Could you please guide?

**Comment by SaiUpadhyayula** [comment]
@javaHelper It's been a while, sorry for the late reply, are you still facing this issue?

**Comment by javaHelper** [comment]
Hi Sai,

Both GET and POST is not working simultaneously. Now with your suggestions POST is working, but not GET. Could you please take a look?

**Comment by SaiUpadhyayula** [comment]
@javaHelper It's been a while, but I uploaded the correct fix for this problem on my channel - you can view the updated video here- https://www.youtube.com/watch?v=nGcVzBMjEGg , the relevant part starts from 13:22

The solution was to consider API Gateway as an OAuth2 Resource Server instead of an OAuth2 Client.

I also updated the repository with these changes, have a look at them once

**Comment by javaHelper** [comment]
Thanks, I will follow all your videos again and will create the code again. Do you've any source code repo?

**Comment by SaiUpadhyayula** [comment]
> Thanks, I will follow all your videos again and will create the code again. Do you've any source code repo?

I updated the API gateway in this repo, have a look at the latest commit changes

**Comment by javaHelper** [comment]
Great Thanks. Will you also update read me?

**Comment by javaHelper** [comment]
Can you guide us how can this be deployed on Azure ?
