### ISSUE TITLE
DDL Mysql

### ISSUE THREAD

**Issue by gabber3000** [SaiUpadhyayula/springboot-microservices-project#7]
Where do I find the DDL to create the tables in the mysql database? Thank you

**Comment by rashed-08** [comment]
Will create automatically if you annotate @entity in a domain class.

**Comment by xdevhk** [comment]
Would you mind guiding me on what reason redirect to the microservices-realm login page again when post HTTP:// localhost:8080/api/order via postman and after login the microservices-realm? So it cannot place an order. Thanks a lot.

**Comment by gabber3000** [comment]
Tanks

**Comment by rashed-08** [comment]
I'm also looking for a solution. [Gateway redirects to login](https://github.com/SaiUpadhyayula/springboot-microservices-project/issues/5). Though I didn't apply yet myself.

**Comment by SaiUpadhyayula** [comment]
The redirect problem should be now solved, I updated the API gateway to resolve the issue, solution is to consider API gateway as a Resource Server instead of Client.

Checkout this revised video which explains the changes, starts from 13:22 https://youtu.be/nGcVzBMjEGg

@gabber3000 @xdevhk @rashed-08

**Comment by rashed-08** [comment]
Thank you @SaiUpadhyayula
